konji/konj/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from . import views

app_name = 'konj'

urlpatterns = [

    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('getSearchResults', views.getSearchResults, name='getSearchResults'),
    path('info', views.info, name="info"),

    path('registration',views.registration, name='registration'),
    path('register/',views.register, name='register'),
    path('login',views.login, name='login'),
    path('auth/', views.auth, name='auth'),
    #path('uporabnik_home', views.uporabnik_home, name='uporabnik_home'),
    path('uporabnik_index', views.uporabnik_index, name='uporabnik_index'),
    path('profil', views.profil, name='profil'),
    path('profil_update/', views.profil_update, name='profil_update'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('profilna_slika/', views.profilna_slika, name='profilna_slika'),
    path('dodaj_slika', views.dodaj_slika, name='dodaj_slika'),

    path('dodaj_slika_konj/<int:id>', views.dodaj_slika_konj, name='dodaj_slika_konj'),
    path('upload/', views.upload, name='upload'),
    path('upload_konj/<int:id>', views.upload_konj, name='upload_konj'),
    path('dodaj_konja', views.dodaj_konja, name='dodaj_konja'),
    path('klic_dodaj_konja', views.klic_dodaj_konja, name='klic_dodaj_konja'),
    path('klic_izbrisi_sliko_konja',views.klic_izbrisi_sliko_konja,name='klic_izbrisi_sliko_konja'),
    path('spremeni_konja/<int:id>',views.spremeni_konja,name='spremeni_konja'),
    path('klic_spremeni_konja', views.klic_spremeni_konja, name='klic_spremeni_konja'),
    path('izbrisi_konja', views.izbrisi_konja, name='izbrisi_konja'),

]

#path('articles/<slug:title>/<int:section>/', views.section, name='article-section'),

konji/konji/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('konj.urls')),
]

konji/konj/views.py
import os

from django.shortcuts import render
from django.template.loader import render_to_string
import json
# Create your views here.
from django.http import HttpResponse
from django.http import JsonResponse
from django.template import loader
#from django.contrib.auth.hashers import make_password
from passlib.hash import pbkdf2_sha256
from django.db import connection
# Create your views here.
from datetime import datetime
from datetime import timedelta

from django.db.models import Q

from .models import *
from django import forms
from django.shortcuts import redirect

from django.views.decorators.csrf import ensure_csrf_cookie
# Create your views here.


max_st_slik = 4

def home(request):
    pasme = Pasma.objects.all().values()
    kategorije = Kategorija.objects.all().values()
    rokovanja = Rokovanje.objects.all().values()
    jahljivosti = Jahljivost.objects.all().values()
    regije = Regija.objects.all().values()

    konji = Konj.objects.all()
    starostMinMin = min(konj.starostKonja or 0 for konj in konji)
    starostMaxMax = max(konj.starostKonja or 0 for konj in konji)
    tezaMinMin = min(konj.tezaKonja or 0 for konj in konji)
    tezaMaxMax = max(konj.tezaKonja or 0 for konj in konji)
    visinaMinMin = min(konj.visinaKonja or 0 for konj in konji)
    visinaMaxMax = max(konj.visinaKonja or 0 for konj in konji)

    ID_Uporabnik = request.session.get('id', -1)
    # preveri sejo
    if not Oseba.objects.filter(osebaID=ID_Uporabnik).exists() or ID_Uporabnik == -1:
        return render(request, 'konj/home.html', {
            'pasme': pasme,
            'kategorije': kategorije,
            'rokovanja': rokovanja,
            'jahljivosti': jahljivosti,
            'regije': regije,
            'starostMinMin': starostMinMin,
            'starostMaxMax': starostMaxMax,
            'tezaMinMin': tezaMinMin,
            'tezaMaxMax': tezaMaxMax,
            'visinaMinMin': visinaMinMin,
            'visinaMaxMax': visinaMaxMax
        })

    return render(request, 'konj/uporabnik_home.html', {
        'pasme': pasme,
        'kategorije': kategorije,
        'rokovanja': rokovanja,
        'jahljivosti': jahljivosti,
        'regije': regije,
        'starostMinMin': starostMinMin,
        'starostMaxMax': starostMaxMax,
        'tezaMinMin': tezaMinMin,
        'tezaMaxMax': tezaMaxMax,
        'visinaMinMin': visinaMinMin,
        'visinaMaxMax': visinaMaxMax
    })


def search(request):
    pasme = Pasma.objects.all().values()
    kategorije = Kategorija.objects.all().values()
    rokovanja = Rokovanje.objects.all().values()
    jahljivosti = Jahljivost.objects.all().values()
    regije = Regija.objects.all().values()

    pasmaSelected = request.GET.get('pasma', '')
    if pasmaSelected == '':
        pasmaSelected = []
    else:
        pasmaSelected = pasmaSelected.split(',')

    kategorijaSelected = request.GET.get('kategorija', '')
    if kategorijaSelected == '':
        kategorijaSelected = []
    else:
        kategorijaSelected = kategorijaSelected.split(',')

    rokovanjeSelected = request.GET.get('rokovanje', '')
    if rokovanjeSelected == '':
        rokovanjeSelected = []
    else:
        rokovanjeSelected = rokovanjeSelected.split(',')

    jahljivostSelected = request.GET.get('jahljivost', '')
    if jahljivostSelected == '':
        jahljivostSelected = []
    else:
        jahljivostSelected = jahljivostSelected.split(',')

    regijaSelected = request.GET.get('regija', '')
    if regijaSelected == '':
        regijaSelected = []
    else:
        regijaSelected = regijaSelected.split(',')

    starostMin = request.GET.get('starostMin', '')
    starostMax = request.GET.get('starostMax', '')

    tezaMin = request.GET.get('tezaMin', '')
    tezaMax = request.GET.get('tezaMax', '')

    visinaMin = request.GET.get('visinaMin', '')
    visinaMax = request.GET.get('visinaMax', '')

    konji = Konj.objects.all()
    starostMinMin = min(konj.starostKonja or 0 for konj in konji)
    starostMaxMax = max(konj.starostKonja or 0 for konj in konji)
    tezaMinMin = min(konj.tezaKonja or 0 for konj in konji)
    tezaMaxMax = max(konj.tezaKonja or 0 for konj in konji)
    visinaMinMin = min(konj.visinaKonja or 0 for konj in konji)
    visinaMaxMax = max(konj.visinaKonja or 0 for konj in konji)
    #starostMinMin = min(konj.starostKonja for konj in konji)
    #starostMaxMax = max(konj.starostKonja for konj in konji)
    #tezaMinMin = min(konj.tezaKonja for konj in konji)
    #tezaMaxMax = max(konj.tezaKonja for konj in konji)
    #visinaMinMin = min(konj.visinaKonja for konj in konji)
    #visinaMaxMax = max(konj.visinaKonja for konj in konji)

    ID_Uporabnik = request.session.get('id', -1)
    # preveri sejo
    if not Oseba.objects.filter(osebaID=ID_Uporabnik).exists() or ID_Uporabnik == -1:
        return render(request, 'konj/search.html', {
            'pasme': pasme,
            'kategorije': kategorije,
            'rokovanja': rokovanja,
            'jahljivosti': jahljivosti,
            'regije': regije,
            'pasmaSelected': pasmaSelected,
            'kategorijaSelected': kategorijaSelected,
            'rokovanjeSelected': rokovanjeSelected,
            'jahljivostSelected': jahljivostSelected,
            'regijaSelected': regijaSelected,
            'starostMin': starostMin,
            'starostMax': starostMax,
            'tezaMin': tezaMin,
            'tezaMax': tezaMax,
            'visinaMin': visinaMin,
            'visinaMax': visinaMax,
            'starostMinMin': starostMinMin,
            'starostMaxMax': starostMaxMax,
            'tezaMinMin': tezaMinMin,
            'tezaMaxMax': tezaMaxMax,
            'visinaMinMin': visinaMinMin,
            'visinaMaxMax': visinaMaxMax
        })

    return render(request, 'konj/uporabnik_search.html', {
        'pasme': pasme,
        'kategorije': kategorije,
        'rokovanja': rokovanja,
        'jahljivosti': jahljivosti,
        'regije': regije,
        'pasmaSelected': pasmaSelected,
        'kategorijaSelected': kategorijaSelected,
        'rokovanjeSelected': rokovanjeSelected,
        'jahljivostSelected': jahljivostSelected,
        'regijaSelected': regijaSelected,
        'starostMin': starostMin,
        'starostMax': starostMax,
        'tezaMin': tezaMin,
        'tezaMax': tezaMax,
        'visinaMin': visinaMin,
        'visinaMax': visinaMax,
        'starostMinMin': starostMinMin,
        'starostMaxMax': starostMaxMax,
        'tezaMinMin': tezaMinMin,
        'tezaMaxMax': tezaMaxMax,
        'visinaMinMin': visinaMinMin,
        'visinaMaxMax': visinaMaxMax
    })

def getSearchResults(request):
    pasmaSelected = request.GET.get('pasma', '')
    if pasmaSelected == '':
        pasmaSelected = []
    else:
        pasmaSelected = pasmaSelected.split(',')

    kategorijaSelected = request.GET.get('kategorija', '')
    if kategorijaSelected == '':
        kategorijaSelected = []
    else:
        kategorijaSelected = kategorijaSelected.split(',')

    rokovanjeSelected = request.GET.get('rokovanje', '')
    if rokovanjeSelected == '':
        rokovanjeSelected = []
    else:
        rokovanjeSelected = rokovanjeSelected.split(',')

    jahljivostSelected = request.GET.get('jahljivost', '')
    if jahljivostSelected == '':
        jahljivostSelected = []
    else:
        jahljivostSelected = jahljivostSelected.split(',')

    regijaSelected = request.GET.get('regija', '')
    if regijaSelected == '':
        regijaSelected = []
    else:
        regijaSelected = regijaSelected.split(',')

    starostMin = request.GET.get('starostMin', '')
    starostMax = request.GET.get('starostMax', '')

    tezaMin = request.GET.get('tezaMin', '')
    tezaMax = request.GET.get('tezaMax', '')

    visinaMin = request.GET.get('visinaMin', '')
    visinaMax = request.GET.get('visinaMax', '')

    sorting = request.GET.get('sorting', '')

    my_filter_qs = Q()

    if len(pasmaSelected) > 0:
        my_filter_qs = my_filter_qs & Q(konjID__pasmaID__in=pasmaSelected)

    if len(rokovanjeSelected) > 0:
        my_filter_qs = my_filter_qs & Q(konjID__rokovanjeID__in=rokovanjeSelected)

    if len(jahljivostSelected) > 0:
        my_filter_qs = my_filter_qs & Q(konjID__jahljivostID__in=jahljivostSelected)
    
    if len(regijaSelected) > 0:
        my_filter_qs = my_filter_qs & Q(konjID__regijaID__in=regijaSelected)

    ponudbe = Ponudba.objects.filter(
        my_filter_qs).select_related()

    res = []
    for ponudba in ponudbe:
        row = {}

        row["konj"] = {}
        row["konj"]["imeKonja"] = ponudba.konjID.imeKonja
        row["konj"]["starostKonja"] = ponudba.konjID.starostKonja
        if (row["konj"]["starostKonja"] == None):
            row["konj"]["starostKonja"] = -1
        row["konj"]["tezaKonja"] = ponudba.konjID.tezaKonja
        if (row["konj"]["tezaKonja"] == None):
            row["konj"]["tezaKonja"] = -1
        row["konj"]["visinaKonja"] = ponudba.konjID.visinaKonja
        if (row["konj"]["visinaKonja"] == None):
            row["konj"]["visinaKonja"] = -1

        kategorije = SpadaVKategorijo.objects.filter(konjID=ponudba.konjID.konjID)
        row["konj"]["kategorije"] = []
        katSelected = False
        for kategorija in kategorije:
            kategorijaRow = {}
            kategorijaRow["imeKategorije"] = kategorija.kategorijaID.imeKategorije
            kategorijaRow["opisKategorije"] = kategorija.kategorijaID.opisKategorije
            row["konj"]["kategorije"].append(kategorijaRow)

            if str(kategorija.kategorijaID.kategorijaID) in kategorijaSelected:
                katSelected = True
        
        if not katSelected and len(kategorijaSelected) > 0:
            continue

        row["ponudba"] = {}
        row["ponudba"]["ponudbaID"] = ponudba.ponudbaID
        row["ponudba"]["cena"] = ponudba.cena
        if (row["ponudba"]["cena"] == None):
            row["ponudba"]["cena"] = -1

        row["oseba"] = {}

konji/konj/templates/konj/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Konj.net</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">

    <script src="{% static 'bootstrapSlider/bootstrap-slider.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrapSlider/bootstrap-slider.min.css' %}">

    <link rel="stylesheet" href="{% static 'bootstrap-overwrite.css' %}">

    {% block imports %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Konji.net</a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="/login">Ustvari ponudbo</a>
                    <a class="nav-item nav-link" href="/login">Prijava</a>
                    <a class="nav-item nav-link" href="/registration">Registracija</a>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-3">
        <img src="{% static 'media/horses-croped.webp' %}" class="img-fluid mx-auto d-block home-back-img" alt="horses">
    </div>
    {% block body %}{% endblock %}
    <footer class="page-footer font-small bg-dark text-white">
        <div class="container">
            <div class="py-2">
                TPO konji.net
            </div>
        </div>
    </footer>
</body>
</html>

konji/konj/templates/konj/dodaj_konja.html
{% extends "konj/uporabnik_base.html" %}

{% load static %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="{% static 'konj/dodaj_konja/dodaj_konja.css' %}">
{% endblock %}

{% block body %}
<div id="forma">
<form name="form" method='POST' enctype=multipart/form-data action="javascript:dodaj()">

  <div class="container">
    <h1>Dodaj ponudbo</h1>
    <p>Izpolnite podatke, da lahko dodate ponudbo. <br> Vsi atributi kateri imajo <font color="red">*</font> so za vnos obvezni.</p>
    <hr> <br>

    <h3>Osnovni podatki </h3><br>

       <label for="konj_ime"><b>Ime konja<font color="red">*</font></b></label><br>
            <input type="text" placeholder="Vnesite ime konja" maxlength="150" id="konj_ime" name="konj_ime" required>


        <label for="starost"><b>Vnesite starost konja v mesecih<font color="red">*</font></b></label><br>
            <input type="number" placeholder="Vnesite starost " maxlength="150" id="starost" name="starost" required>


        <label for="visinaID"><b>Vnesite višino konja(cm)<font color="red">*</font></b></label><br>
            <input type="text" placeholder="Vnesite celoštevilsko vrednost v cm. " maxlength="150" id="visinaID" name="visinaID" required>

        <label for="cena"><b>Vnesite ceno konja<font color="red">*</font></b></label><br>
            <input type="text" placeholder="Vnesite celoštevilsko vrednost v €. " maxlength="150" id="cena" name="cena" required>


      <b>Označite vse kategorije v katere spada konj<font color="red">*</font></b> <br>
          {% for kategorija in kategorije %}

            <input type="checkbox" name="kategorija" value="{{ kategorija.kategorijaID }}"> {{ kategorija.imeKategorije }} <br>
          {% endfor %}
          <br><br>

      <h3>Pasma </h3><br>
        <label for="pasmaID"><b>Pasma konja<font color="red">*</font></b></label>
            <select id="pasmaID" class="izbira">
                <option value="-1"> Pritisnite da izberete pasmo konja</option>
                {% for pasma in pasma %}
                    <option value="{{ pasma.pasmaID }}"> {{ pasma.pasmaIme }} </option>
                {% endfor %}
            </select>


      <h3>Podrobnejši podatki </h3><br>
      <label for="rodovnik_bool"><b>Ima rodovnik<font color="red">*</font></b></label>
            <select id="rodovnik_bool" class="izbira">
                <option value="-1"> Pritisnite da izberete rodovnik</option>
                <option value="1">Da</option>
                <option value="0">Ne</option>

            </select>


      <p> <b>Če ste pri rodovniku izbrali "Da" morate obvezno dodati sliko rodovnika.</b> </p>
       <!-- <input id="image" type="file" class="" name="image">!-->
      <input type="file" id="image_to_upload"/>


      <h3>Jahljivost </h3><br>
        <label for="jahljivost"><b>Je jahljiv<font color="red">*</font></b></label>
            <select id="jahljivost" class="izbira">
                <option value="-1"> Pritisnite da izberete jahljivost</option>
                {% for jahljivost in jahljivost %}
                    <option value="{{ jahljivost.jahljivostID }}">{{ jahljivost.imeJahljivosti }}</option>
                {% endfor %}
            </select>

      <h3>Rokovanje </h3><br>
        <label for="rokovanje"><b>Je rokljiv<font color="red">*</font></b></label>
            <select id="rokovanje" class="izbira">
                <option value="-1"> Pritisnite da izberete rokljivost</option>
                {% for rokovanje in rokovanje %}
                    <option value="{{ rokovanje.rokovanjeID }}">{{ rokovanje.imeRokovanja }}</option>
                {% endfor %}
            </select>

    <h3>Opis </h3><br>
      <label for="konj_opis"><b>Opis konja <font color="red">*</font></b></label>
            <label class="textareaContainer">
             <textarea placeholder="Na kratko opišite konja." maxlength="1000" id="konj_opis"></textarea>
            </label>

    <h3>Stanje konja </h3><br>
      <label for="poskodbe"><b>Opis poškodb</b></label>
            <label class="textareaContainer">
             <textarea placeholder="Na kratko opišite poškodbe konja če jih ima." maxlength="500" id="poskodbe"></textarea>
            </label>
      <label for="bolezni"><b>Opis bolezni</b></label>
            <label class="textareaContainer">
             <textarea placeholder="Na kratko opišite bolezni konja če jih ima." maxlength="500" id="bolezni"></textarea>
            </label>
       <label for="rezultati"><b>Rezultati</b></label>
            <label class="textareaContainer">
             <textarea placeholder="Tukaj dodajte link do rezultatov, če jih konj ima." maxlength="500" id="rezultati"></textarea>
            </label>
       <label for="link_konjeniska_zveza"><b>Konjeniška zveza</b></label>
            <label class="textareaContainer">
          <textarea placeholder="Tukaj dodajte link do konjeniške zveze." maxlength="500" id="link_konjeniska_zveza"></textarea>
            </label>
      <b>Označite na katerih pregledih je že bil konj <font color="red">*</font></b> <br>
          {% for pregled in pregledi %}

            <input type="checkbox" name="pregled" value="{{ pregled.vrstaPregledaID }}"> {{ pregled.imePregleda }} <br>
          {% endfor %}
          <br><br>


     <h3>Lokacija </h3><br>
        <label for="regijaID"><b>Regija konja<font color="red">*</font></b></label>
            <select id="regijaID" class="izbira">
                <option value="-1"> Pritisnite da izberete regijo konja</option>
                {% for regija in regije %}
                    <option value="{{ regija.regijaID }}"> {{ regija.imeRegije }} </option>
                {% endfor %}
            </select>

<h3>Lastnik<font color="red">*</font></h3><br>
      <label for="lastnik"><b>Izberite "Da", če ste lastnik konja<font color="red">*</font></b></label>
            <select id="lastnik" class="izbira">
                <option value="1">Da</option>
                <option value="0">Ne</option>
            </select>
    <p id="status" style="text-align:center"></p>
    <div class="row justify-content-center">
        <button type="submit" class="btn btn-primary" id="dodaj">Dodaj konja</button>
    </div>
  </div>

</form>
</div>
<script src="{% static 'konj/dodaj_konja/dodaj_konja.js' %}"></script>
{% endblock %}

konji/konj/templates/konj/dodaj_slika.html
{% extends "konj/uporabnik_base.html" %}

{% load static %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="{% static 'konj/dodaj_slika/dodaj_slika.css' %}">
{% endblock %}

{% block body %}
<div id="forma">
<h5>Trenutna profilna slika: </h5><br>
    <img id="{{ profilna_slika }}" src="{% static profilna_slika %}"  width="300" height="300" alt="Ni slike">

<br><br><br>
{% load static %}
<h5>Zamenjaj profilno sliko: </h5>
<form action="{% url 'konj:upload' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        <h6>1. Najprej izberite sliko:</h6>
        <input id="id_image" type="file" class="" name="image">
    </p>
    <h6>2. Nato je oddate:</h6>
    <div class="row justify-content-center">
        <button type="submit" value="Submit" class="btn btn-primary" /> Dodaj sliko </button>
    </div>
</form><br>

</div>
{% endblock %}

konji/konj/templates/konj/login.html
{% extends "konj/login_register_base.html" %}

{% load static %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="{% static 'konj/login/login.css' %}">
{% endblock %}

{% block body %}
<script src="{% static 'konj/login/login.js' %}"></script>

<div id="forma">
    <form method='POST' action="javascript:login()">
                {% csrf_token %}
            <div class="imgcontainer" id=naslov>
                <h2>Prijava</h2>
            </div>

            <div class="container">
            <label for="uname"><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="uname" id="usr" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" id="pss" required>

            <div class="row justify-content-center">
                <!-- <button type="submit" class="registerbtn" onclick="login();">Prijava</button> -->
                <button type="submit" class="btn btn-primary" onclick="login();">Prijava</button>
            </div>

            </div>

            <div class="container" id="status" style="color:red; text-align: center; background-color:#f1f1f1">
            </div>
            <p><center>Še nimate računa? <a href="{% url 'konj:registration' %}" >Registracija</a></center></p>
        </form>
</div>
{% endblock %}

konji/konj/templates/konj/uporabnik_index.html
{% extends "konj/uporabnik_base.html" %}

{% load static %}

{% block imports %}
<link rel="stylesheet" type="text/css" href="{% static 'konj/uporabnik_index/uporabnik_index.css' %}">
{% endblock %}

{% block body %}
<script src="{% static 'konj/uporabnik_index/uporabnik_index.js' %}"></script>

<div class="container">
    {% for konj in konji %}
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <div class="card ponudbaSlika d-flex justify-content-center align-items-center">
                        {% if konj.konj.slika %}
                            <img src="{{ res.konj.slika }}" class="img-fluid" alt="slika konja">
                        {% else %}
                            <label class="p-2">Ni slike</label>
                        {% endif %}
                    </div>
                </div>
                <div class="col-8">
                    <div class="row">
                        <div class="col-6">
                            <div>
                                Ime: {{ konj.konj.imeKonja }}
                            </div>
                            <hr/>
                            <div>
                                {% if konj.konj.starostKonja != -1 %}
                                    Starost: {{ konj.konj.starostKonja }} mes
                                {% else %}
                                    Starost:
                                {% endif %}
                            </div>
                            <hr/>
                            <div>
                                {% if konj.konj.tezaKonja != -1 %}
                                    Teža: {{ konj.konj.tezaKonja }} kg
                                {% else %}
                                    Teža:
                                {% endif %}
                            </div>
                            <hr/>
                            <div>
                                {% if konj.konj.visinaKonja != -1 %}
                                    Višina: {{ konj.konj.visinaKonja }} cm
                                {% else %}
                                    Višina:
                                {% endif %}
                            </div>
                            <hr/>
                            <div>
                                Pasma: {{ konj.konj.pasma.imePasme }}
                            </div>
                            <hr/>
                            <div>
                                Rokovanje: {{ konj.konj.rokovanje.imeRokovanja }}
                            </div>
                            <hr/>
                            <div>
                                Jahljivost: {{ konj.konj.jahljivost.imeJahljivosti }}
                            </div>
                        </div>
                        <div class="col-6 d-flex flex-column">
                            <div>
                                Regija: {{ konj.konj.regija.imeRegije }}
                            </div>
                            <hr/>
                            <div>
                                Kategorije: 
                                {% for kategorija in konj.konj.kategorije %}
                                    {% if not forloop.last %}
                                        {{ kategorija.imeKategorije }},
                                    {% else %}
                                        {{ kategorija.imeKategorije }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <hr/>
                            <div>
                                Cena: {{ konj.ponudba.cena }} €
                            </div>
                            <div class="d-flex flex-column align-items-end mt-auto m-3">
                                <div class="row">
                                    <a href="{% url  'konj:spremeni_konja' id=konj.konjID %}" class="btn btn-primary" role="button" aria-pressed="true">Spremeni ponudbo</a>
                                </div>
                                <div class="row mt-1">
                                    <a href="{% url  'konj:dodaj_slika_konj' id=konj.konjID %}" class="btn btn-primary" role="button" aria-pressed="true">Dodaj sliko konja</a>
                                </div>
                                <div class="row mt-1">
                                    <a href="javascript:izbrisi('{{ konj.konjID }}')" class="btn btn-primary" role="button" aria-pressed="true">Izbriši ponudbo</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script src="{% static 'konj/uporabnik_index/uporabnik_index.js' %}"></script>
{% endblock %}